# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\meshimagewidget.ui'
#
# Created: Fri May  6 10:37:58 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MeshImageWidget(object):
    def setupUi(self, MeshImageWidget):
        MeshImageWidget.setObjectName("MeshImageWidget")
        MeshImageWidget.resize(884, 640)
        self.horizontalLayout = QtGui.QHBoxLayout(MeshImageWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtGui.QGroupBox(MeshImageWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonContinue = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonContinue.setObjectName("pushButtonContinue")
        self.horizontalLayout_3.addWidget(self.pushButtonContinue)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.listWidget = QtGui.QListWidget(self.groupBox_3)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonViewAll = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonViewAll.setObjectName("pushButtonViewAll")
        self.horizontalLayout_2.addWidget(self.pushButtonViewAll)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelAngle = QtGui.QLabel(self.groupBox_2)
        self.labelAngle.setObjectName("labelAngle")
        self.verticalLayout_6.addWidget(self.labelAngle)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditAngle = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditAngle.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditAngle.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEditAngle.setObjectName("lineEditAngle")
        self.horizontalLayout_7.addWidget(self.lineEditAngle)
        self.horizontalSliderAngle = QtGui.QSlider(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSliderAngle.sizePolicy().hasHeightForWidth())
        self.horizontalSliderAngle.setSizePolicy(sizePolicy)
        self.horizontalSliderAngle.setMaximum(100)
        self.horizontalSliderAngle.setProperty("value", 50)
        self.horizontalSliderAngle.setSliderPosition(50)
        self.horizontalSliderAngle.setTracking(False)
        self.horizontalSliderAngle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderAngle.setObjectName("horizontalSliderAngle")
        self.horizontalLayout_7.addWidget(self.horizontalSliderAngle)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.widgetZinc = SceneviewerWidget(MeshImageWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetZinc.sizePolicy().hasHeightForWidth())
        self.widgetZinc.setSizePolicy(sizePolicy)
        self.widgetZinc.setObjectName("widgetZinc")
        self.horizontalLayout.addWidget(self.widgetZinc)

        self.retranslateUi(MeshImageWidget)
        QtCore.QMetaObject.connectSlotsByName(MeshImageWidget)

    def retranslateUi(self, MeshImageWidget):
        MeshImageWidget.setWindowTitle(QtGui.QApplication.translate("MeshImageWidget", "Mesh/Image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MeshImageWidget", "Mesh/Image Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MeshImageWidget", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonContinue.setText(QtGui.QApplication.translate("MeshImageWidget", "Continue", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MeshImageWidget", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonViewAll.setText(QtGui.QApplication.translate("MeshImageWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MeshImageWidget", "Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAngle.setText(QtGui.QApplication.translate("MeshImageWidget", "Angle:", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.sceneviewerwidget import SceneviewerWidget
